with staging as (
    select * from {{ ref('stg_siconv_proposta') }}
)

select
    id_proposta,
    uf_proponente,
    municipio_proponente,
    codigo_municipio_ibge,
    codigo_orgao_superior,
    descricao_orgao_superior,
    natureza_juridica,
    numero_proposta,
    dia_proposta,
    mes_proposta,
    ano_proposta,
    data_proposta,
    codigo_orgao,
    descricao_orgao,
    modalidade,
    identificacao_proponente,
    nome_proponente,
    cep_proponente,
    endereco_proponente,
    bairro_proponente,
    nome_banco,
    situacao_conta,
    situacao_projeto_basico,
    situacao_proposta,
    data_inicio_vigencia_proposta,
    data_fim_vigencia_proposta,
    objeto_proposta,
    item_investimento,
    enviada_mandataria,
    nome_subtipo_proposta,
    descricao_subtipo_proposta,
    valor_global_proposta,
    valor_repasse_proposta,
    valor_contrapartida_proposta,
    codigo_agencia,
    codigo_conta,
    __ingested_at_utc,
    __ingestion_run_id,
    __source_file,
    __source_sha256
from staging
