with source as (
    select * from {{ source('bronze', 'siconv_convenio') }}
),

renamed_and_typed as (
    select
        {{ sha256_surrogate_key([
            'NR_CONVENIO',
            'ID_PROPOSTA',
            'DIA',
            'MES',
            'ANO',
            'DIA_ASSIN_CONV',
            'SIT_CONVENIO',
            'SUBSITUACAO_CONV',
            'SITUACAO_PUBLICACAO',
            'INSTRUMENTO_ATIVO',
            'IND_OPERA_OBTV',
            'NR_PROCESSO',
            'UG_EMITENTE',
            'DIA_PUBL_CONV',
            'DIA_INIC_VIGENC_CONV',
            'DIA_FIM_VIGENC_CONV',
            'DIA_FIM_VIGENC_ORIGINAL_CONV',
            'DIAS_PREST_CONTAS',
            'DIA_LIMITE_PREST_CONTAS',
            'DATA_SUSPENSIVA',
            'DATA_RETIRADA_SUSPENSIVA',
            'DIAS_CLAUSULA_SUSPENSIVA',
            'SITUACAO_CONTRATACAO',
            'IND_ASSINADO',
            'MOTIVO_SUSPENSAO',
            'IND_FOTO',
            'QTDE_CONVENIOS',
            'QTD_TA',
            'QTD_PRORROGA',
            'VL_GLOBAL_CONV',
            'VL_REPASSE_CONV',
            'VL_CONTRAPARTIDA_CONV',
            'VL_EMPENHADO_CONV',
            'VL_DESEMBOLSADO_CONV',
            'VL_SALDO_REMAN_TESOURO',
            'VL_SALDO_REMAN_CONVENENTE',
            'VL_RENDIMENTO_APLICACAO',
            'VL_INGRESSO_CONTRAPARTIDA',
            'VL_SALDO_CONTA',
            'VALOR_GLOBAL_ORIGINAL_CONV'
        ]) }} as id_convenio_observacao,
        {{ clean_string('NR_CONVENIO') }} as numero_convenio,
        try_cast(ID_PROPOSTA as bigint) as id_proposta,
        try_cast(DIA as smallint) as dia_assinatura,
        try_cast(MES as smallint) as mes_assinatura,
        try_cast(ANO as smallint) as ano_assinatura,
        {{ parse_date_br('DIA_ASSIN_CONV') }} as data_assinatura_convenio,
        {{ clean_string('SIT_CONVENIO') }} as situacao_convenio,
        {{ clean_string('SUBSITUACAO_CONV') }} as subsituacao_convenio,
        {{ clean_string('SITUACAO_PUBLICACAO') }} as situacao_publicacao,
        {{ parse_boolean_sim_nao('INSTRUMENTO_ATIVO') }} as is_instrumento_ativo,
        {{ parse_boolean_sim_nao('IND_OPERA_OBTV') }} as is_opera_obtv,
        {{ clean_string('NR_PROCESSO') }} as numero_processo,
        {{ clean_string('UG_EMITENTE') }} as unidade_gestora_emitente,
        {{ parse_date_br('DIA_PUBL_CONV') }} as data_publicacao_convenio,
        {{ parse_date_br('DIA_INIC_VIGENC_CONV') }} as data_inicio_vigencia_convenio,
        {{ parse_date_br('DIA_FIM_VIGENC_CONV') }} as data_fim_vigencia_convenio,
        {{ parse_date_br('DIA_FIM_VIGENC_ORIGINAL_CONV') }} as data_fim_vigencia_original,
        try_cast(DIAS_PREST_CONTAS as int) as dias_prestacao_contas,
        {{ parse_date_br('DIA_LIMITE_PREST_CONTAS') }} as data_limite_prestacao_contas,
        {{ parse_date_br('DATA_SUSPENSIVA') }} as data_suspensiva,
        {{ parse_date_br('DATA_RETIRADA_SUSPENSIVA') }} as data_retirada_suspensiva,
        try_cast(DIAS_CLAUSULA_SUSPENSIVA as int) as dias_clausula_suspensiva,
        {{ clean_string('SITUACAO_CONTRATACAO') }} as situacao_contratacao,
        {{ parse_boolean_sim_nao('IND_ASSINADO') }} as is_assinado,
        {{ clean_string('MOTIVO_SUSPENSAO') }} as motivo_suspensao,
        {{ parse_boolean_sim_nao('IND_FOTO') }} as is_foto,
        try_cast(QTDE_CONVENIOS as smallint) as quantidade_convenios,
        try_cast(QTD_TA as smallint) as quantidade_termos_aditivos,
        try_cast(QTD_PRORROGA as smallint) as quantidade_prorrogacoes,
        {{ parse_decimal_br('VL_GLOBAL_CONV') }} as valor_global_convenio,
        {{ parse_decimal_br('VL_REPASSE_CONV') }} as valor_repasse_convenio,
        {{ parse_decimal_br('VL_CONTRAPARTIDA_CONV') }} as valor_contrapartida_convenio,
        {{ parse_decimal_br('VL_EMPENHADO_CONV') }} as valor_empenhado_convenio,
        {{ parse_decimal_br('VL_DESEMBOLSADO_CONV') }} as valor_desembolsado_convenio,
        {{ parse_decimal_br('VL_SALDO_REMAN_TESOURO') }} as valor_saldo_remanescente_tesouro,
        {{ parse_decimal_br('VL_SALDO_REMAN_CONVENENTE') }} as valor_saldo_remanescente_convenente,
        {{ parse_decimal_br('VL_RENDIMENTO_APLICACAO') }} as valor_rendimento_aplicacao,
        {{ parse_decimal_br('VL_INGRESSO_CONTRAPARTIDA') }} as valor_ingresso_contrapartida,
        {{ parse_decimal_br('VL_SALDO_CONTA') }} as valor_saldo_conta,
        {{ parse_decimal_br('VALOR_GLOBAL_ORIGINAL_CONV') }} as valor_global_original_convenio,
        count(*) over (partition by NR_CONVENIO) as source_conflict_count,
        (count(*) over (partition by NR_CONVENIO) > 1) as has_source_conflict,
        __ingested_at_utc,
        __ingestion_run_id,
        __source_file,
        __source_sha256
    from source
)

select * from renamed_and_typed
