name: 'lakehouse_transferencias_discricionarias_legais'
version: '1.0.0'
config-version: 2

profile: 'dbt_lakehouse'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lakehouse_transferencias_discricionarias_legais:
    staging:
      +materialized: ephemeral
    silver:
      +materialized: table
      +file_format: delta
      +schema: silver
      +pre-hook:
        - "SET spark.sql.parquet.datetimeRebaseModeInWrite=CORRECTED"
        - "SET spark.sql.parquet.datetimeRebaseModeInRead=CORRECTED"
        - "SET spark.sql.parquet.int96RebaseModeInWrite=CORRECTED"
        - "SET spark.sql.parquet.int96RebaseModeInRead=CORRECTED"