dbt_lakehouse:
  outputs:
    dev:
      host: spark-thrift-server
      method: thrift
      port: 10000
      schema: default
      threads: 1
      thrift_transport: binary
      type: spark
  target: dev